### ISSUE TITLE
add info on adjusting image size to images.md

### ISSUE THREAD

**Issue by kchatlosh** [DHRI-Curriculum/html-css#38]
something like this guide @smythp created would be great to add into that images.md section:
https://github.com/smythp/github-images-test

**Comment by kchatlosh** [comment]
and would be good to add this info on public domain and open license images that you pulled up during the workshop: https://openlab.citytech.cuny.edu/blog/help/following-copyright-guidelines-for-images/

**Comment by dhinstitutes** [comment]
@kchatlosh and @hackettka - these seem like suggestions that you may want to incorporate into the curriculum before we do the final push to create a GitBook. Is that correct?

**Comment by kallewesterling** [comment]
@hackettka adding you as an assignee here. If you want, I can go ahead and make a pull request and suggest the changes. Let me know!

**Comment by hackettka** [comment]
Thanks @kchatlosh ! These are good to think about. I think patrick's image guide doesn't make sense for the images.md - height and width adjustments are CSS, whereas the images.md section is talking about HTML. And otherwise the CSS for height and width is included in the CSS section - on the "Useful Selectors" page. I will add the copyright guidelines for images to the images.md page. 

Thanks @kchatlosh and @kallewesterling !

**Comment by kallewesterling** [comment]
Thank you for reviewing this issue as well @hackettka!
