### ISSUE TITLE
lessons.md reviewed

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/html-css#52]
- Look at your workshop on [the website](http://kallewesterling.pythonanywhere.com) to see what your workshop currently looks like, and what looks like it needs to change.
- Think about order and transitions—do the lessons follow a logical pattern and is it working? Do you need to add something somewhere? Are the transitions between the lessons clear?
- Can you add a challenge at the end of the lesson that summarizes what the learner has learned, and activates the knowledge in an interactive way.
- Think about the length of the lessons — are they too long? Too short? In general, each lesson should cover one topic, or one particular skill — or perhaps connect two skills. If you find that you’re covering more than that in one lesson, perhaps they should be split into more than one.
- While reviewing the lessons.md file, think about vocabulary terms that we should add in an easily accessible "dictionary" for our learners.

Feel free to reach out to me and @lmrhody and ask for help, if you need it. Also feel free to involve others in the group!

**Comment by kallewesterling** [comment]
If you want another view of the Markdown and how it is being translated/parsed into the website, you can see [this link](https://kallewesterling.pythonanywhere.com/preview). It is a new tool that I created that will download the live markdown from GitHub and preview the way that the website interprets the markdown. In order to access it, you'll have to be logged in using `admin` as your login and `admin` as your password!

Once you're logged in, you can click "Preview in parser" and it should show you what the live markdown is, and how the website will interpret your markdown.

**Comment by paramajmera** [comment]
The more I look at my lessons, the more I seem to think that we ought to really pare down the focus on html / css formatting and put a lot more emphasis on platforms / CMS. Given where we are with building websites today, making sites with just HTML/CSS simply doesn't cut it anymore. A more robust overview of platforms / CMS can help participants actually learn how to acquire domains and put up websites that look a lot more professional and have many more features. I keep thinking about how helping participants understand how reclaim hosting + wordpress + omeka + storymaps can be used together to build archives, or to perform digital storytelling, or to make course websites can be so much more rewarding than the time we spend on thinking about how CSS styling works.

**Comment by kallewesterling** [comment]
@paramajmera I think it's important to remember that the DHRI has as its mission "foundational concepts" and while you're right in assuming that many people today operate their websites with CMS tools like Wordpress, Wix, or Ghost, the folks who attend DHRI should come out with an understanding of the foundational tools and concepts — that is, the stuff that lie behind those CMS tools. That's why we have institute pre-readings like Meredith Broussard's book on Artificial Unintelligence, and that's why the participants should learn HTML and CSS. For many of their imagined projects, they will (or might) need to go beyond the CMS:s to write their own snippets or full-on code examples. If someone, for example, wants to implement a [D3 visualization](https://d3js.org/) on their website, they'd need to know a lot of fundamental markup language (both HTML and SVG) as well as some scripting knowledge (beyond what we currently do in the DHRI).

And yes, there will be frustration both on our end and the participants' end, that we "want to get to the thing itself" (that is, digital storytelling, or building an archive) but there are plenty of other workshops offered for those things — and there may be room in the future for the DHRI to develop those as well — but for the time being, the DHRI grant is very specific in its scope and mission: to provide the participants with a fundamental knowledge of the building blocks behind the shiny, fancy tools.

I hope that can help contextualize what we're doing here and how it can be both helpful and useful for you as an instructor, and for the DHRI participants as well!

**Comment by paramajmera** [comment]
Thank you Kalle your reply puts the HTML workshop in much clearer perspective. I wasn't aware of exactly how the grant was written and how much flexibility we have in changing the courses. I'm glad to hear that we've assigned Broussard's book as a pre-reading. I won't bring up the CMS / platforms idea for the time being and I'll keep it in my back pocket as a future workshop that we might do some other time.

**Comment by hackettka** [comment]
Hi all, I'm going to look over this workshop tomorrow I hope, but I do think it makes sense to include more than we have previously on platforms. It is also foundational to understanding the web and websites and the browser as an environment..This was really clear based on participant's reactions after the workshop I put together for DRI this winter. I would be happy to help use some summer hours to translate this in this style if that makes sense: https://docs.google.com/presentation/d/11ZSjt7p3mJ6ruRviwWy62FiLoAwS0rgiTvnuqZYYwMs/edit?usp=sharing

**Comment by hackettka** [comment]
Hi Param, overall, this looks good! It doesn't look like too much has changed since I last taught the workshop, so my suggestions are mostly about adjusting it to this very different format of taking the workshop. I'm also seeing some a few other things that seem like technical issues.. ? Anyway: 

Adjusting to the new format - More prefacing and clarification would be good throughout:
- I think there is a lot of clarifying info that I used to say aloud during the workshop that is not here and maybe should be added in. Specifically, I emphasized a lot about the interaction between the languages and the browser and explained more about what the computer or software is doing when you say X or Y. For example, in lesson #6 with absolute and relative links, I would explain that a key difference is whether you're telling the browser to look in the same folder for a file or to go out on the internet to find the file.
- Relatedly, I would add more explanation about CSS and what 'cascading style sheets' means in lesson #10 for the same reasons as the above bullet point.
- In lesson #12 I think you can give a bit more intro to the rules - that they style specific elements across the site, or can be specific to one element on one page. 
- The"conventions" page was good during the in-person workshop because it acted as a recap page. Usually, I would be including this information throughout the 1st part of the workshop, and use this section to just clarify what we had discussed. In this format, this page actually introduces new content. I think this information should also be integrated into the parts of the previous sections, where appropriate. 
- There are two times when participants are prompted to review the command line - lessons #9 and #11. Solutions are given as external links that actually are broken. I think it might make more sense to structure this as a challenge and solution section. I also think you might want to link to the command line workshop. 
- In lesson #9 I think the part about building the html doc should be a separate section within that lesson. 
- for Lesson #13, i would go ahead and tell them to try is, maybe as a challenge. We usually do that during the workshop.

Also overall, there's a lot of sections to this workshop, and in the in-person workshop I think it works fine, but here, it feels choppy. Also, I think seeing that the lesson has 20 sections can be overwhelming to the user. I feel like some of what are now discrete lessons could be combined as different sections of one lesson. For example, I could see Basic HTML page and tags and elements combined, maybe paragraphs and headings too. Images and Links could also be one lesson. CSS Basics, rules sets, filtering and classes and IDs could be combined and i would move the integrating section to after that and include the challenge with it. 

Other things
- The nesting of the the HTML and CSS throughout is not happening in the codeblocks. It makes it difficult to read the code, and doesn't show best practices.
- In multiple places the 'solution' appears before the 'challenge'. In lessons #3, #5, #6, #12 
- Also, to maintain consistency with the other workshops, the header for the solutions should be changed to "Solutions". Right now its "What should happen" and the like. 
- In a couple places the text is wrapping around the image in a way that is confusing to the reader. Not sure if this is a note for you or Kalle. See Lesson #5 and #7 

Lastly, I think the making website public should be updated significantly based on the info in the slideshow i previously shared.

**Comment by paramajmera** [comment]
Thank you so much for these suggestions, @hackettka ! I will work on incorporating them all.

@kallewesterling @lmrhody I would really appreciate meeting to discuss how we might redo the final "making the website public" section.

**Comment by kallewesterling** [comment]
@paramajmera  I'll reach out to you about this ASAP

**Comment by dyoong** [comment]
So sorry for being so late in my review, but I agree with what Kristen mentioned with adding more clarification throughout the workshop can help to contextualize what you're doing at each part. I also think that maybe a little more screenshots to illustrate what you mean, particularly when you're applying CSS (like the hierarchy of application) can be helpful.

In addition to the written rationale for why CSS should be linked to an external stylesheet (Option 3), perhaps also mention that in the newest HTML (or HTML5) version inline attributes are slowly being deprecated so browsers may not even read the styles associated with particular elements of the html.

**Comment by kallewesterling** [comment]
I didn't know that they were being deprecated, @dyoong — this is good to know. Where did you find information about it?

Mozilla's [web docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style) about the `style` attribute doesn't mention it. In fact, it's a recommended for `HTML5` use.

**Comment by kallewesterling** [comment]
@dyoong were you able to find anymore info about the deprecation warning you raised here? Just want to make sure to catch that before this issue is closed and forgotten about.

**Comment by paramajmera** [comment]
@kallewesterling I thought the Mozilla link suggested that inline styling is still a thing?

**Comment by kallewesterling** [comment]
@paramajmera yes, that's why I was curious as to what @dyoong knew beyond what I've been able to read :)
